# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'skull.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(20, 20, 761, 531))
        self.stackedWidget.setObjectName("stackedWidget")
        self.Home = QtWidgets.QWidget()
        self.Home.setObjectName("Home")
        self.stackedWidget.addWidget(self.Home)
        self.Sign_In = QtWidgets.QWidget()
        self.Sign_In.setObjectName("Sign_In")
        self.Email_Input = QtWidgets.QLineEdit(self.Sign_In)
        self.Email_Input.setGeometry(QtCore.QRect(310, 160, 141, 31))
        self.Email_Input.setObjectName("Email_Input")
        self.Password_Input = QtWidgets.QLineEdit(self.Sign_In)
        self.Password_Input.setGeometry(QtCore.QRect(310, 220, 141, 31))
        self.Password_Input.setObjectName("Password_Input")
        self.label_Title_Sign_in = QtWidgets.QLabel(self.Sign_In)
        self.label_Title_Sign_in.setGeometry(QtCore.QRect(310, 100, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(10)
        self.label_Title_Sign_in.setFont(font)
        self.label_Title_Sign_in.setTextFormat(QtCore.Qt.AutoText)
        self.label_Title_Sign_in.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Title_Sign_in.setWordWrap(True)
        self.label_Title_Sign_in.setIndent(2)
        self.label_Title_Sign_in.setObjectName("label_Title_Sign_in")
        self.label_eMail = QtWidgets.QLabel(self.Sign_In)
        self.label_eMail.setGeometry(QtCore.QRect(180, 160, 121, 21))
        self.label_eMail.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_eMail.setObjectName("label_eMail")
        self.label_Password = QtWidgets.QLabel(self.Sign_In)
        self.label_Password.setGeometry(QtCore.QRect(180, 220, 121, 21))
        self.label_Password.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Password.setObjectName("label_Password")
        self.Log_In = QtWidgets.QPushButton(self.Sign_In)
        self.Log_In.setGeometry(QtCore.QRect(330, 260, 91, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.Log_In.setFont(font)
        self.Log_In.setObjectName("Log_In")
        self.stackedWidget.addWidget(self.Sign_In)
        self.Sign_up = QtWidgets.QWidget()
        self.Sign_up.setObjectName("Sign_up")
        self.stackedWidget.addWidget(self.Sign_up)
        self.User_Page = QtWidgets.QWidget()
        self.User_Page.setObjectName("User_Page")
        self.label = QtWidgets.QLabel(self.User_Page)
        self.label.setGeometry(QtCore.QRect(70, -10, 661, 511))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../Desktop/tbc homeWork/TBC_HomeWork-1/Registration-Successful-Message-Example-In-HTML.png"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.Log_Out = QtWidgets.QPushButton(self.User_Page)
        self.Log_Out.setGeometry(QtCore.QRect(240, 410, 321, 91))
        self.Log_Out.setObjectName("Log_Out")
        self.stackedWidget.addWidget(self.User_Page)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_Title_Sign_in.setText(_translate("MainWindow", "Sign In"))
        self.label_eMail.setText(_translate("MainWindow", "E-Mail:"))
        self.label_Password.setText(_translate("MainWindow", "Password"))
        self.Log_In.setText(_translate("MainWindow", "Log In"))
        self.Log_Out.setText(_translate("MainWindow", "Log_Out"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
